# Generated by Django 3.1.2 on 2020-10-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20201004_0330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales', models.IntegerField(max_length=200)),
                ('label', models.IntegerField(max_length=200)),
                ('cost', models.IntegerField(max_length=200)),
                ('msrp', models.IntegerField(max_length=200)),
                ('month', models.IntegerField(max_length=200)),
                ('mon', models.IntegerField(max_length=200)),
                ('tues', models.IntegerField(max_length=200)),
                ('wed', models.IntegerField(max_length=200)),
                ('thurs', models.IntegerField(max_length=200)),
                ('fri', models.IntegerField(max_length=200)),
                ('sat', models.IntegerField(max_length=200)),
                ('sun', models.IntegerField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='greeting',
            name='BarcodeNum',
            field=models.IntegerField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='greeting',
            name='SKUNum',
            field=models.IntegerField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='greeting',
            name='industry',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
