# Generated by Django 3.1.2 on 2020-10-04 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20201004_0523'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dataset',
            new_name='Datasetmodel',
        ),
    ]
