# Generated by Django 3.1.2 on 2020-10-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20201004_0552'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales', models.DecimalField(decimal_places=2, max_digits=250)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=250)),
                ('msrp', models.DecimalField(decimal_places=2, max_digits=250)),
                ('month', models.IntegerField(max_length=2)),
                ('mon', models.IntegerField(max_length=200)),
                ('tues', models.IntegerField(max_length=200)),
                ('wed', models.IntegerField(max_length=200)),
                ('thurs', models.IntegerField(max_length=200)),
                ('fri', models.IntegerField(max_length=200)),
                ('sat', models.IntegerField(max_length=200)),
                ('sun', models.IntegerField(max_length=200)),
                ('SKU', models.IntegerField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales', models.DecimalField(decimal_places=2, max_digits=250)),
                ('label', models.DecimalField(decimal_places=2, max_digits=250)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=250)),
                ('msrp', models.DecimalField(decimal_places=2, max_digits=250)),
                ('month', models.IntegerField(max_length=2)),
                ('mon', models.IntegerField(max_length=200)),
                ('tues', models.IntegerField(max_length=200)),
                ('wed', models.IntegerField(max_length=200)),
                ('thurs', models.IntegerField(max_length=200)),
                ('fri', models.IntegerField(max_length=200)),
                ('sat', models.IntegerField(max_length=200)),
                ('sun', models.IntegerField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Datasetmodel',
        ),
    ]
