# Generated by Django 3.1.2 on 2020-10-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_auto_20201004_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='greeting',
            name='Month',
            field=models.IntegerField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
